- name: Send notification deployment pull request
  uri:
    url: https://hooks.slack.com/services/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
    method: POST
    body: '{"channel": "#technical", "username": "deplou", "text": "Pull request {{pull_request}} deployed : http://{{ansible_host}}:42{{pull_request}}."}'
    body_format: json
    HEADER_Content-Type: "application/json"
  when: pull_request is defined

- name: Send notification deployment branch
  uri:
    url: https://hooks.slack.com/services/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
    method: POST
    body: '{"channel": "#technical", "username": "deplou", "text": "Branch {{branch|default(master)}} deployed : http://{{ansible_host}}/{{branch|default(master)}}."}'
    body_format: json
    HEADER_Content-Type: "application/json"
  when:
    - pull_request is undefined
